config/routes.rb
Shbct::Application.routes.draw do
	namespace :admin do
    get '', to: 'dashboard#index', as: '/'

    get 'users'                         => 'users#index'
    match 'update'                      => 'users#update',        via: [:post, :patch]
    get 'edit_user/:id'                 => 'users#edit',   				as: 'edit_user'
    delete 'delete_user/:id'            => 'users#delete_user', 	as: 'delete_user'
    get 'inactive'                      => 'users#inactive'

    get 'events'                        => 'events#index'
    #resources :events
  end
  
  mount API => '/'

  devise_for :users, controllers: {sessions: "sessions"}
  root :to => 'home#index'

  post 'api/v1/accounts/create'         => 'home#create'
  post 'api/v1/accounts/sign_in'        => 'home#create_session'
  post 'api/v1/accounts/sign_out'       => 'home#delete_session'
  post 'api/v1/accounts/create_account' => 'home#create_account'
  
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  layout 'admin'
  before_filter :authenticate_admin

  def index
  	@events = Event.all.paginate(page: params[:page], :per_page => 10)
  	respond_to do |format|
      format.html
      format.json { render json: @events }
    end
	end
end

app/views/admin/events/index.html.haml
.container
  .row.first-row
    .span2
      %h3 All Events
  .row    
    %table.table.table-hover.table-condensed.table-bordered.table-striped
      %thead
        %tr
          %th Event Name
          %th Location
          %th Date
          %th Event's User
          %th Invited Friends
          %th Action
      %tbody
        - @events.each do |event|
          %tr
            %td= event.name
            %td= event.location
            %td= event.date            
            %td= event.user.user_name
            %td= event.friends.count
            %td
              /= link_to(edit_admin_event_path(event), class: 'btn btn-mini') do
              /  %i.icon-pencil
              /= link_to(admin_event_path(event), class: 'btn btn-mini', method: :delete, data: {confirm: "Are you sure"}) do
              /  %i.icon-trash
      %tfoot
        %tr
          %td{:colspan=>6}
            = will_paginate @events if @events.present?
    