config/routes.rb
Shbct::Application.routes.draw do
	namespace :admin do
    get '', to: 'dashboard#index', as: '/'

    get 'users'                         => 'users#index'
    match 'update'                      => 'users#update',        via: [:post, :patch]
    get 'edit_user/:id'                 => 'users#edit',   				as: 'edit_user'
    delete 'delete_user/:id'            => 'users#delete_user', 	as: 'delete_user'
    get 'inactive'                      => 'users#inactive'

    get 'events'                        => 'events#index'
    #resources :events
  end
  
  mount API => '/'

  devise_for :users, controllers: {sessions: "sessions"}
  root :to => 'home#index'

  post 'api/v1/accounts/create'         => 'home#create'
  post 'api/v1/accounts/sign_in'        => 'home#create_session'
  post 'api/v1/accounts/sign_out'       => 'home#delete_session'
  post 'api/v1/accounts/create_account' => 'home#create_account'
  
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  ROLES = ['admin', 'insights', 'tester', 'content creator', 'publisher', 'master admin']
  SOCIAL_STATE = %w[facebook twitter google]

  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable
         
  ## Database authenticatable
  field :email,                     :type => String, :default => ""
  field :user_name,                 :type => String, :default => ""
  field :phone,                     :type => String, :default => ""
  field :encrypted_password,        :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,      :type => String
  field :reset_password_sent_at,    :type => Time

  ## Rememberable
  field :remember_created_at,       :type => Time

  ## Trackable
  field :sign_in_count,             :type => Integer, :default => 0
  field :current_sign_in_at,        :type => Time
  field :last_sign_in_at,           :type => Time
  field :current_sign_in_ip,        :type => String
  field :last_sign_in_ip,           :type => String

  ## Confirmable
  # field :confirmation_token,      :type => String
  # field :confirmed_at,            :type => Time
  # field :confirmation_sent_at,    :type => Time
  # field :unconfirmed_email,       :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts,         :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,            :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,               :type => Time
  
  field :avatar,                    :type => String     # profile logo image

  field :role,                      :type => String
  field :active,                    :type => Boolean,   :default => true


  field :auth_token,                :type => String
  field :authentication_token,      :type => String
  before_save :ensure_authentication_token

  # ????
  field :event_messages_to_your_phone,            :type => Boolean,   :default => true
  field :event_invitations_to_your_phone,         :type => Boolean,   :default => false
  field :chat_messages_to_your_phone,             :type => Boolean,   :default => false
  field :legal_notices,                           :type => String,    :default => ""
  field :help_faq,                                :type => String,    :default => ""
  field :basic_notifications,                     :type => String,    :default => ""

  # Settings NOtification
  field :event_reminders,           :type => Boolean,   :default => true
  field :chat_notifications,        :type => Boolean,   :default => false
  field :new_friend_events,         :type => Boolean,   :default => true
  field :people_joining_events,     :type => Boolean,   :default => false
  field :people_leaving_events,     :type => Boolean,   :default => false
  field :event_changes,             :type => Boolean,   :default => true

  has_many :friends
  
  def self.search(search)
    if search.present?      
      users = User.or({ :email => /.*#{search}*./ }, { :user_name => /.*#{search}*./ })
      users.where(:role => nil)
    else
      User.where(:role => nil)
    end
  end

  def avata_url
    if self.avatar.url.nil?
      ""
    else
      if Rails.env.production?
        self.avatar.url
      else
        "http://192.168.0.55:3005" + self.avatar.url.gsub("#{Rails.root.to_s}/public/user/", "/user/")
      end
    end
  end
  
  def self.find_by_token(token)
    User.where(:authentication_token=>token).first
  end  

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'
  before_filter :authenticate_admin

  def index
    if params[:search].present?
      @users = User.search(params[:search]).paginate(page: params[:page], :per_page => 10)
    else
      @users = User.all.paginate(page: params[:page], :per_page => 10)  
    end
  	
  	respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end
  
  def edit
    @user = User.find(params[:id])
    @events = @user.events
  end
  # The User profile update
  #
  # @route            
  # @wireframe    
  def update
  end

  
  def account_settings
  end

  def notification_settings
  end

  def settings
  end
  # The User Profile Delete
  #
  # @route            GET /admin/delete_user
  # @wireframe        
  
  def delete_user
    @user = User.find(params[:id])
    @user.destroy unless @user.nil?
    respond_to do |format|
      format.html { redirect_to action: :index}
      format.json { head :no_content}
    end
  end

  # The User Profile Inactive
  #
  # @route            GET /admin/inactive
  # @wireframe          
  def inactive
    @user = User.find(params[:id])
    @user.update_attribute(:active, !@user.active)
    redirect_to :action => :index and return
  end
end

app/views/admin/users/_form.html.haml
.row
	.span2
		= image_tag(@user.avata_url, style:'width: 100px;')
	.span4
		%h5= @user.user_name
		%label 
			Logged in via 
			%span{style:'color:blue;font-weight:600'}= @user.from_social.capitalize
.row	
	= simple_form_for(@user, :url=>admin_update_path, :html=> {class: 'form-horizontal', multipart: true}) do |f|
		- f.object.errors.messages.each do |msg|
			.alert.alert-error= msg[1].first
		= hidden_field_tag :id, @user.id
		.span4{style:'margin-left: 0px;'}
			%h3 Settings
			.row{style:'margin-left: 0px;'}
				.control-group.string.optional.event_messages_to_your_phone{style:'margin-bottom: 0px;'}
					%label{ for: "event_messages_to_your_phone", class: "string optional control-label", style:'width:280px' } Push event messages to your phone?
					.controls{style:'margin-left: 300px;'}
						= check_box_tag :event_messages_to_your_phone, '1', false, name:'user[event_messages_to_your_phone]'
				.control-group.string.optional.event_invitations_to_your_phone{style:'margin-bottom: 0px;'}
					%label{ for: "event_invitations_to_your_phone", class: "string optional control-label", style:'width:280px' } Push event invitations to your phone?
					.controls{style:'margin-left: 300px;'}
						= check_box_tag :event_invitations_to_your_phone, '1', false, name:'user[event_invitations_to_your_phone]'
				.control-group.string.optional.chat_messages_to_your_phone{style:'margin-bottom: 0px;'}
					%label{ for: "chat_messages_to_your_phone", class: "string optional control-label", style:'width:280px' } Push chat messages to your phone?
					.controls{style:'margin-left: 300px;'}
						= check_box_tag :chat_messages_to_your_phone, '1', false, name:'user[chat_messages_to_your_phone]'
			.row{style:'margin-left: 0px;'}
				%h5 Reminders
				.control-group.string.optional.event_messages_to_your_phone{style:'margin-bottom: 0px;'}
					%label{ for: "validate", class: "string optional control-label", style:'width:280px' } You haven't validated your email address with Head-count. Do you want to do it now?
					.controls{style:'margin-left: 300px;'}
						
				.control-group.string.optional.event_invitations_to_your_phone{style:'margin-bottom: 0px;'}
					%label{ for: "new_event", class: "string optional control-label", style:'width:280px' } You haven't started your own even yet!
					.controls{style:'margin-left: 300px;'}
						
			.row{style:'margin-left: 0px;'}
				%h5 Regal Notices
				%p= @user.legal_notices				
			.row{style:'margin-left: 0px;'}
				%h5 Help & FAQ
				%p= @user.help_faq
		.span4{style:'margin-left: 0px;'}
			%h3 Account Settings
			.row{style:'margin-left: 0px;'}
				.control-group.string.optional.user_name{style:'margin-bottom: 0px;'}
					%label{ for: "user_name", class: "string optional control-label"} SHBCT Username :
					.controls{style:'margin-top:5px;'}
						%strong= @user.user_name
				.control-group.string.optional.user_name{style:'margin-bottom: 0px;'}
					%label{ for: "email", class: "string optional control-label"} Email Address :
					.controls{style:'margin-top:5px;'}
						%strong= @user.email
				.control-group.string.optional.user_name{style:'margin-bottom: 0px;'}
					%label{ for: "phone", class: "string optional control-label"} Phone Number :
					.controls{style:'margin-top:5px;'}
						%strong= @user.phone
		.span4{style:'margin-left: 0px;'}
			%h3 Notifications Settings
			.control-group.string.optional.event_reminders{style:'margin-bottom: 0px;'}
				%label{ for: "event_reminders", class: "string optional control-label"} Event Reminders
				.controls
					= check_box_tag :event_reminders, '1', @user.event_reminders, name:'user[event_reminders]'	
			.control-group.string.optional.chat_notifications{style:'margin-bottom: 0px;'}
				%label{ for: "chat_notifications", class: "string optional control-label"} Chat Notifications
				.controls
					= check_box_tag :chat_notifications, '1', @user.chat_notifications, name:'user[chat_notifications]'
			.control-group.string.optional.new_friend_events{style:'margin-bottom: 0px;'}
				%label{ for: "new_friend_events", class: "string optional control-label"} NewFriend's Events
				.controls
					= check_box_tag :new_friend_events, '1', @user.new_friend_events, name:'user[new_friend_events]'
			.control-group.string.optional.people_joining_events{style:'margin-bottom: 0px;'}
				%label{ for: "people_joining_events", class: "string optional control-label"} People Joining Events
				.controls
					= check_box_tag :people_joining_events, '1', @user.people_joining_events, name:'user[people_joining_events]'
			.control-group.string.optional.people_leaving_events{style:'margin-bottom: 0px;'}
				%label{ for: "people_leaving_events", class: "string optional control-label"} People Leaving Events
				.controls
					= check_box_tag :people_leaving_events, '1', @user.people_leaving_events, name:'user[people_leaving_events]'
			.control-group.string.optional.event_changes{style:'margin-bottom: 0px;'}
				%label{ for: "event_changes", class: "string optional control-label"} Event Changes
				.controls
					= check_box_tag :event_changes, '1', @user.event_changes, name:'user[event_changes]'
.row		
	%h3 Event List
	%table.table.table-hover.table-condensed.table-bordered.table-striped
		%thead
			%tr
				%th Event Name
				%th Location
				%th Date
				%th Event's User
				%th Invited Friends
		%tbody
			- @events.each do |event|
				%tr
					%td= event.name
					%td= event.location
					%td= event.date						
					%td= event.user.user_name
					%td= event.friends.count
		%tfoot
			%tr
				%td{:colspan=>6}
					= will_paginate @events if @events.present?	
.row.last-row
	.form-actions
		= link_to "Back", admin_users_path, class:'btn btn-danger'

app/views/admin/users/edit.html.haml
.container
  .row.header-row{style:'border-bottom: 1px solid #000000; margin-bottom:20px;'}
    .span8{style:'margin-left: 0px;'}
      %h3{style:'margin-bottom: 0px;'} User Profile - Account Info
    .span3.pull-right{style:'margin-right: 30px;'}
      %strong.pull-right{style:'font-size: 16px;margin-top: 25px;'}
        Status :
        = @user.active == true ? "Active" : "De-Active"
    .span1.pull-right
  = render "form"

app/views/admin/users/index.html.haml
.container
  .row.first-row
    .span8
      %h3 SHBCT Users
    .span4{style:'margin-top:20px;'}
      = form_tag admin_users_path, method: 'get', :class=>'form-search', :id=>'user_search_form' do
        .input.input-prepend{style:'width:80%;'}
          %button{type:'submit',class:'btn'} 
            &nbsp;
            %i.icon-search{:onclick=>'javascript:$("#user_search_form").submit()',style:'margin-left: -5px;margin-top:4px;'}
          = text_field_tag 'search', params[:search], :class=>'span3 search-query', style:'padding-left:5px;padding-right:5px;width:100%;'
          %span.fornav-end
            %i.icon-remove-sign{:onclick=>'javascript:$("#user_search_form .search-query").val(""); $("#user_search_form").submit()'}
  .row.customers-contents
    %table.table.table-striped.table-hover.table-bordered
      %thead
        %tr
          %th Email            
          %th User Name            
          %th App Visits            
          %th Actions
      %tbody
        - @users.reject{|u| User::ROLES.include?(u.role)}.each do |u|
          %tr
            %td= u.email.index('@')==49 ? u.email[13..21]+'@twitter.com' : u.email
            %td= u.user_name
            %td= u.sign_in_count
            %td
              = link_to(admin_edit_user_path(u), class: 'btn btn-mini', :"data-no-turbolink"=>true) do
                %i.icon-book

              = link_to(admin_delete_user_path(u), class: 'btn btn-mini', method: :delete, data: {confirm: "Are you sure"}) do
                %i.icon-trash
      %tfoot
        %tr
          %td{colspan: 11}
            = will_paginate @users