config/routes.rb
Shbct::Application.routes.draw do
	namespace :admin do
    get '', to: 'dashboard#index', as: '/'

    get 'users'                         => 'users#index'
    match 'update'                      => 'users#update',        via: [:post, :patch]
    get 'edit_user/:id'                 => 'users#edit',   				as: 'edit_user'
    delete 'delete_user/:id'            => 'users#delete_user', 	as: 'delete_user'
    get 'inactive'                      => 'users#inactive'

    get 'events'                        => 'events#index'
    #resources :events
  end
  
  mount API => '/'

  devise_for :users, controllers: {sessions: "sessions"}
  root :to => 'home#index'

  post 'api/v1/accounts/create'         => 'home#create'
  post 'api/v1/accounts/sign_in'        => 'home#create_session'
  post 'api/v1/accounts/sign_out'       => 'home#delete_session'
  post 'api/v1/accounts/create_account' => 'home#create_account'
  
end

app/views/layouts/_admin_nav.html.haml
%a.btn.btn-navbar{:"data-toggle"=>"collapse", :"data-target"=>".nav-collapse"}
  %span.icon-th-list
= link_to "SHBCT", admin_path, :class => 'brand'
.nav-collapse.collapse
  %ul.nav.nav-justified
    - if current_page?(admin_path)
      %li.active
        = link_to "Home", admin_path
    - else
      %li
        = link_to "Home", admin_path

    %li
      = link_to "Users", admin_users_path  
    %li
      = link_to "Events", admin_events_path
    %li
      = link_to "Content", "#"
    %li
      = link_to "My Account", "#"
    %li.dropdown{id:'submenu2'}
      %a.dropdown-toggle{:href=>"#submenu2", :'data-toggle'=>"dropdown"} 
        Settings
        %b.caret
      %ul.dropdown-menu{:role=>"menu"}
        %li
          = link_to "APP Settings", "#"
        %li.last
          = link_to "...", "#"
  %ul.nav.pull-right
    %li
      = link_to "Log Out", destroy_user_session_path, :method => :delete
:css
  .nav-justified li:hover{
    background-color: #E6E6E6;
    box-shadow: 0 3px 8px rgba(0, 0, 0, 0.125) inset;
    color: #555555;
    text-decoration: none;
  }
  ul.nav li.dropdown ul.dropdown-menu li{
    padding: 0px;
  }
  
  .dropdown-submenu .dropdown-menu{
    display: none !important;
  }
  .dropdown-submenu:hover .dropdown-menu{
    display: block !important;
  }

app/views/layouts/_footer.html.haml
.footer

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class=>("alert alert-#{name == :notice ? "success" : "error"}")}
      %a.close{:"data-dismiss"=>"alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to image_tag('logo.png'), root_path, :class => 'brand'
%ul.nav.pull-left
  - if current_user.present?
    %li
      = link_to "Projects", "#"
    %li
      = link_to "Calendar", "#"
    %li
      = link_to "Everything", "#"  
    %li
      = link_to "Progress", "#"
    %li
      = link_to "Everyone", "#"
    %li
      = link_to "Me", "#"
%ul.nav.pull-right
  - if current_user.present?
    - if current_user.role == "admin"
      %li
        = link_to "Admin Dashboard", "/admin"    
    %li
      = link_to "Sign out", destroy_user_session_path, :method => :delete
      = link_to "Upgrades", '#'
      = link_to "Account", '#'
      = link_to "New features", '#'      
      
      = form_tag root_path, method: 'get', :class=>'form-search navbar-form', :id=>'user_search_form' do        
        %i.icon-search{style:'left: 5px;position: absolute;top: 34px;'}       
        = text_field_tag 'search', params[:search], :class=>'span3', style:'', placeholder:'Jump to a project, persor, label, or search...'
  

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SHBCT</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller].gsub("/","_")%>_<%= params[:action]%>">
  
  <div class="navbar navbar-fixed-top">
    <nav class="navbar-inner">
      <div class="container">
        <%= render 'layouts/admin_nav' %>
      </nav>
    </div>
  </div>

  <div class="container">
    <%= render 'layouts/messages'%>
  </div>
  <div id="main_content">
    <div class="container">
      <%= yield %>
    </div>        
  </div>
  <footer>
    <%= render 'layouts/footer'%>
  </footer>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SHBCT</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller]%>_<%= params[:action]%>">
	
	<div class="navbar navbar-fixed-top">
		<nav class="navbar-inner">
			<div class="container">
				<%= render 'layouts/navigation' %>
			</nav>
		</div>
	</div>

	<div class="container">
		<%= render 'layouts/messages'%>
	</div>
	<div id="main_content">
		<div class="container">
			<%= yield %>
		</div>				
	</div>
	<footer>
		<%= render 'layouts/footer'%>
	</footer>
</body>
</html>